### ISSUE TITLE
Bitrate output is always 0

### ISSUE THREAD

**Issue by vredesbyyrd** [mariusor/mpris-ctl#12]
With flac or mp3, the bitrate variable always outputs 0. Tested with lollypop and mpd.

**Comment by mariusor** [comment]
Hi, I see you closed this issue, I imagine it's because this could be what the player actually reports. 

But just to humor me, could you please add the output for:

    $ dbus-send --print-reply --type=method_call  \
     --dest=org.mpris.MediaPlayer2.PLAYERNAME \
     /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
     string:org.mpris.MediaPlayer2.Player string:Metadata

Where `org.mpris.MediaPlayer2.PLAYERNAME` is what you get after you run (most probably `org.mpris.MediaPlayer2.mpd`: 

    $ dbus-send --print-reply --type=method_call \
     --dest=org.freedesktop.DBus / \
     org.freedesktop.DBus.ListNames | grep mpris.MediaPlayer2

**Comment by vredesbyyrd** [comment]
Hey, no sweat. I ended doing something completly different to 
accomplish my goal of getting the bitrate info of the currently playing 
song in lollypop, because after reading a bit about mpris2 i was under 
the impression that you could not get bit rate data. As in its not a 
valid metadata variable anymore. Though it appears you could with 
mpris1. Thats why i deleted the bug report. I could be completely wrong 
about this, though.

Here is the output you requested, a ran it with lollypop as the player, 
since thats my go to player right now.

method return time=1513032895.768404 sender=:1.88 -> destination=:1.982 
serial=2665 reply_serial=2
   variant       array [
         dict entry(
            string "mpris:trackid"
            variant                object path 
"/org/gnome/Lollypop/TrackId/14593680"
         )
         dict entry(
            string "xesam:trackNumber"
            variant                int32 3
         )
         dict entry(
            string "xesam:title"
            variant                string "Dust"
         )
         dict entry(
            string "xesam:album"
            variant                string "Interstellar: Original 
Motion Picture Soundtrack (Deluxe Version)"
         )
         dict entry(
            string "xesam:artist"
            variant                array [
                  string "Hans Zimmer"
               ]
         )
         dict entry(
            string "xesam:albumArtist"
            variant                array [
                  string "Hans Zimmer"
               ]
         )
         dict entry(
            string "mpris:length"
            variant                int64 341000000
         )
         dict entry(
            string "xesam:genre"
            variant                array [
                  string "Soundtrack"
               ]
         )
         dict entry(
            string "xesam:url"
            variant                string 
"file:///mnt/696AEA387920C07B/Music/Scores/Hans%20Zimmer/Interstellar%20-%20Deluxe%20-%202014/03%20-%20Dust.flac"
         )
         dict entry(
            string "xesam:userRating"
            variant                double 0
         )
         dict entry(
            string "mpris:artUrl"
            variant                string 
"file:///home/clu/.cache/lollypop/Hans Zimmer_Interstellar Original 
Motion Picture Soundtrack Deluxe Version_2014_900.jpg"
         )
      ]

**Comment by mariusor** [comment]
So, I think this is a player issue, you might want to submit a ticket to them.

For Clementine, this is what I get:

    dbus-send --print-reply --type=method_call   --dest=org.mpris.MediaPlayer2.clementine  /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get  string:org.mpris.MediaPlayer2.Player string:Metadata     
    method return time=1513063286.443492 sender=:1.3789 -> destination=:1.3792 serial=24 reply_serial=2                                                                                                          
       variant       array [                                                                                                                                                                                     
             dict entry(                                                                                                                                                                                         
                string "bitrate"                                                                                                                                                                                 
                variant                int32 256                                                                                                                                                                 
             )                                                                                                                                                                                                   
             dict entry(                                                                                                                                                                                         
                string "mpris:artUrl"                                                                                                                                                                            
                variant                string "file:///tmp/clementine-art-g19358.jpg"                                                                                                                            
             )                                                                                                                                                                                                   
             dict entry(                                                                                                                                                                                         
                string "mpris:length"                                                                                                                                                                            
                variant                int64 665000000                                                                                                                                                           
             )                                                                                                                                                                                                   
             dict entry(                                                                                                                                                                                         
                string "mpris:trackid"                                                                                                                                                                           
                variant                string "/org/mpris/MediaPlayer2/Track/9"                                                                                                                                  
             )                                                                                                                                                                                                   
             dict entry(                                                                                                                                                                                         
                string "xesam:album"                                                                                                                                                                             
                variant                string "Where the Sea Gives Up Its Dead"                                                                                                                                  
             )                                                                                                                                                                                                   
             dict entry(                                                                                                                                                                                         
                string "xesam:artist"                                                                                                                                                                            
                variant                array [                                                                                                                                                                   
                      string "Draugadróttinn"                                                                                                                                                                    
                   ]                                                                                                                                                                                             
             ) 
    ....

And `mpris-ctl` shows:

    mpris-ctl info "%track_name:%bitrate"
    The Sun of the War-Gods:256

**Comment by vredesbyyrd** [comment]
Okay, thank you for all the info. Thats good to know. The developer of 
lollypop said he will not be adding the option to view bit rate 
info/metadata etc. from within the interface because "that stuffs for 
nerds"....which is probably the case for the majority. But its useful 
'nerd' info in many regards i would argue. More so when you have become 
accustomed to viewing it from years of foobar2000 and ncmpcpp use. Im 
going to submit a ticket requesting the abiltiy to atleast be able to 
fetch that data with other tools like yours. That seems like a good 
comprimise to me. And your tool seems like the best solution i have 
seen.

Thanks again
