### ISSUE TITLE
Collaboration proposal

### ISSUE THREAD

**Issue by ghost** [mariusor/mpris-ctl#14]
First of all, thanks for such a piece of software!

I was using it in the last few months when I was on Arch Linux, and it was all I was searching for; I had tried `playerctl`, but it does too much for my taste.

Now that I changed to [Void Linux](http://voidlinux.eu) with [musl libc](http://musl-libc.org) and kind of lost access to Spotify &mdash; it doesn't work with musl, neither does Google Winedive, as they're linked against glibc &mdash;, I was searching for other (lightweight) media players and, between one player and another, I started to read your code and read the MPRIS spec and such.

During this, I wrote [playpause](https://github.com/nuskorpios/playpause); it is more minimalistic than yours, because I rarely want to see some metadata. As I wrote in README, "it just plays and pauses your media player".

Anyway, I saw your code and, despite how useful is mpris-ctl, I think the code base can be futher enhanced. With this, I refer to things like [code](https://github.com/mariusor/mpris-ctl/blob/master/src/sdbus.h#L138) [duplication](https://github.com/mariusor/mpris-ctl/blob/master/src/sdbus.h#L603) and some potential [spaghetti code](https://github.com/mariusor/mpris-ctl/blob/master/src/main.c#L291) (it isn't about `goto` &mdash; I [use](https://github.com/nuskorpios/playpause/blob/master/playpause.c#L159) [it](https://github.com/nuskorpios/playpause/blob/master/playpause.c#L159) [myself](https://github.com/nuskorpios/playpause/blob/master/playpause.c#L212)).

I think I can help you with that; I'm writing this issue because, but in addition I think the mpris-ctl "architecture" &mdash; if I can call it that way &mdash; must be modified/enhanced. You can see my code if you're interested.

What you think about it? :)

**Comment by mariusor** [comment]
Feel free to open PRs with code improvements. I will gladly discuss with you on specific points, but by just taking a look at your links I don't understand the exact issues you want to bring to my attention.

Also if you're interested in just the play/pause aspects of the binary, I would gladly accept a PR to hide the info command behind a compile time switch. :)

This is actually my first C project, so I think it's to be expected that code quality is not too high. If you want to see how the code evolved a bit, you can take a look at my other mpris related project: mpris-scrobbler, which is a bit more complicated, and I think would benefit more of a code review and an architecture discussion.

**Comment by ghost** [comment]
You're right; this isn't *really* an issue x) This would be also my first "big" contribution to an open-source project, so I thought I could talk to you on how to improve the code base and design.

I'll open some PRs to address some of the topic I raised.

Anyway, thanks :)
