### ISSUE TITLE
Monitoring changes

### ISSUE THREAD

**Issue by nsbgn** [mariusor/mpris-ctl#15]
Thanks for this useful tool!

I've been toying with the idea of adding a `monitor` option, that works similarly to `status` but continuously outputs a new line, every time the dbus metadata or play status changes. This is helpful for use with statusbars such as [polybar](https://github.com/jaagr/polybar), [yabar](https://github.com/geommer/yabar) or [i3blocks](https://github.com/vivien/i3blocks) - it removes the need for polling, and it's more comfortable than relying on sketchy Python scripts. An example call would be `mpris-ctl monitor '%play_status %artist_name - %album_name'`.

I don't know how much of a hassle it'd be to implement. If you're not up for it, I'm happy to try myself, but it'll be a while, since I haven't written any C before. Either way - would you pull such a change back into your repository? :)

**Comment by mariusor** [comment]
I think that these statusbars support polling a command, so your block needs just to invoke `mpris-ctl info`. 

I'll investigate a bit more to make sure, but I'm pretty sure a monitor command is not neccessary for this use case.

**Comment by nsbgn** [comment]
Ah, yes, they do support a polling command. The point is that I want to avoid polling. The status would be updated only, and immediately, when a relevant event is triggered. i3blocks has a `interval=persist` setting, polybar has `tail=true` and yabar has `type:"persist"` to support this type of behaviour.

With `playerctl`, you'd use their library to create a [script](https://github.com/x70b1/polybar-scripts/tree/master/polybar-scripts/player-mpris-tail) that does this. I guess I could also make a script like that for `mpris-ctl`, but a monitor command seems more elegant to me.

**Comment by mariusor** [comment]
I think this will never be in the scope of mpris-ctl, I'm sorry. I'll go on and close it.
