### ISSUE TITLE
List command support

### ISSUE THREAD

**Issue by vaygr** [mariusor/mpris-ctl#16]
Thanks for this useful program. Apparently `playerctl` is becoming overloaded..

But! Listing existing players functionality could be borrowed and be useful here. There's a flag to specify the player, but there's no way to get the name you'd want to control with `mpris-ctl`.

Something as simple as `--list` flag would be great.

**Comment by mariusor** [comment]
There is already an option for this, though it's maybe not as discoverable as a `--list` flag. You can do `mpris-ctl info %player_name`.

**Comment by mariusor** [comment]
That being said, probably I'll add a shortcut command for it, similar to how there is `status` for `mpris-ctl info %play_status`

**Comment by vaygr** [comment]
Yeah, that all sounds great, thanks a lot.

**Comment by mariusor** [comment]
OK, I've added the `mpris-ctl list` command. No release yet, but if you can compile latest master you'll be able to use it.

**Comment by vaygr** [comment]
Hmm, it should probably be in a separate issue, but it seems a3420a5 broke `--player <player>` functionality.

It simply ignores the value and outputs all players. `active`/`inactive` work fine though.

**Comment by mariusor** [comment]
I'll take a look, thank you, but yes, please open a separate issue.

**Comment by vaygr** [comment]
@mariusor do you think it would be useful to be able to list all players with one command?

Right now I have to use `mpris-ctl --player active` and `mpris-ctl --player inactive` to list playing and paused/stopped players.

`playerctl`'s `--list-all` lists all players available via dbus.

I tried `mpris-ctl --player active,inactive info`, but it didn't work, still listed only active players.

I'm wondering if it's worth fixing that, or introduce `--player all` maybe?

**Comment by vaygr** [comment]
I'm wondering if comma-separated syntax is broken. Just tried this:

```
mpris-ctl --player Spotify,ncspot info
```

Didn't return anything. While separately they work just fine. Maybe `active,inactive` is broken for the same reason?

**Comment by vaygr** [comment]
Nevermind, the manual page was confusing a little. This works:

```
mpris-ctl --player active --player inactive info
```

**Comment by vaygr** [comment]
Maybe the man page / `--help` need some corrections:

- `--player active | inactive | <name,...>`
- `--player <name,...>     Execute command only for player(s) named <name,...>`

Note the comma. Better replace it with `<name> [<name>]...` to avoid confusion?

I also see that active/inactive is a special case, and while `mpris-ctl --player Spotify ncspot info '%player_name - %play_status'` works fine regardless of their status, `mpris-ctl --player active inactive info` doesn't, and needs to have `--player` arg specified twice: `mpris-ctl --player active --player inactive info`, but that's already covered in the man page.

**Comment by mariusor** [comment]
Thanx for your input @vaygr, I'll try to make it more consistent, but no promises on when.

I'll ping you back here sometime in the future.

**Comment by mariusor** [comment]
PS. If you're willing to submit one, I'd accept a PR for adding your suggestions to the man page. Sorry I didn't propose that from the start.

**Comment by vaygr** [comment]
@mariusor opened #26
