### ISSUE TITLE
Ambiguous player names

### ISSUE THREAD

**Issue by vaygr** [mariusor/mpris-ctl#18]
Not sure if it's by design, but mpris-ctl accepts non-existing player names for `--player`.

For example, if you list them and add some suffix at the end, that would work, e.g.:

```shell
$ mpris-ctl list
Audacious
Chromium
$ mpris-ctl --player Audaciousness play
$
```

That could lead to unexpected results in some cases.

**Comment by vaygr** [comment]
To add, in scripting this may be considered as a feature, when you try to get player status and reuse the value to control the player later:

```shell
$ player=$(mpris-ctl info "%player_name:%play_status" | grep "^Audacious:Playing")
$ mpris-ctl --player "${player}" pp
```

But that's still not worth consistency I think.

**Comment by mariusor** [comment]
Good catch, I'll fix it soonish. :)
