### ISSUE TITLE
Output to STDERR

### ISSUE THREAD

**Issue by nedludd** [mariusor/mpris-ctl#19]
Hi, just wondering why you are sending output to STDERR and not STDOUT?

I was trying to get `mpris-ctrl` working with a script and it took me forever to figure out why it wasn't working :-)

**Comment by mariusor** [comment]
Good catch, thank you. 
I'll gladly accept a patch for it if you're interested.

**Comment by nedludd** [comment]
Submitted pull request  15f5972

**Comment by mariusor** [comment]
Thank you. :) 

Merged.

**Comment by mariusor** [comment]
I also tagged a new release: [v0.8.2](https://github.com/mariusor/mpris-ctl/releases/tag/v0.8.2)
