### ISSUE TITLE
pp option is now unusable

### ISSUE THREAD

**Issue by litoj** [mariusor/mpris-ctl#22]
Just a small suggestion. I use your program every day for media playback, but since the update of inactive player interaction, the pp command, which I use the most, loses its purpose as it can only stop everything, or play everything due to the explicit selection of type of players affected. This feature is not much of a feature in my eyes, because this behaviour was already available with stop and play commands.
Do you think you could something about it?

**Comment by mariusor** [comment]
Hey @JosefLitos, apologies again for the long delay.

The way I'm using the pp command is by passing specifically the `active` and `inactive` values to the `--player` flag. 

This is definitely a UX regression, but it still works: `mpris-ctl --player active --player inactive pp`

I don't think I want to do anything else about it at the moment, but if you can submit a proposal that makes sense I'd be willing to entertain it.
