### ISSUE TITLE
Address boundary error

### ISSUE THREAD

**Issue by litoj** [mariusor/mpris-ctl#23]
when trying to execute a command from i3 with a specific player name, such as `Multimediální přehrávač VLC` I receive
```
fish: Job 1, 'bash -c "mpris-ctl --player 'Mu…' terminated by signal SIGSEGV (Address boundary error)
```
if I execute it in an interactive bash shell on its own, it works, but in fish and in noninteractive bash, it doesn't
it is fixed by using `bash -ic` but I wonder why.

**Comment by mariusor** [comment]
This has been fixed in the latest version (v0.8.6).

Apologies for taking this long, I didn't receive notifications of these tickets so I only saw them when someone else pinged me directly.

If you're still interested in using `mpris-ctl` I'd love to know if it works for you now.

**Comment by litoj** [comment]
> If you're still interested in using `mpris-ctl` I'd love to know if it works for you now.

I have currently switched to playerctl but will certainly take a look as soon as I find my old config using mpris-ctl.

Does mpris-ctl allow for changing track position? [Apparently](https://github.com/altdesktop/playerctl/issues/282) that seems to be the only reason I switched.

**Comment by mariusor** [comment]
That's a good feature, but no `mpris-ctl` doesn't support it at the moment. 

I [added it](https://github.com/mariusor/mpris-ctl/issues/25) as a feature request.
