### ISSUE TITLE
Negative seeking arguments don't parse

### ISSUE THREAD

**Issue by Gotolei** [mariusor/mpris-ctl#27]
Title. Forward seeking works correctly, it parses floats and ms/s/m as expected, but trying to format it as a negative number `seek -1` `seek -0.5` `seek -2s` etc all result in it apparently failing to parse and skipping the default interval of 5 seconds ahead instead. I've tried quotes around the number and escaping the -, don't know if there's a trick I'm missing otherwise, but if there is one I'd be interested in hearing it.

0.9.96-1 built from AUR

**Comment by mariusor** [comment]
Hey, sorry for the late reply. 

I'll take a look, as far as I remember I tested negative values, but I must have missed something.

**Comment by mariusor** [comment]
I've released a tag with this fix @Gotolei, thank you for your report. See [v0.9.98](https://github.com/mariusor/mpris-ctl/releases/tag/v0.9.98).

**Comment by Gotolei** [comment]
Yep, it seems good. Thanks for the fix
